name: passive
services:
  frontend:
    image: avr21/tfg-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - passive-bridge
    depends_on:
      - backend

  backend:
    image: avr21/tfg-backend
    restart: always
    ports:
      - "1337:1337"
    networks:
      - passive-bridge
    env_file: .env
    depends_on:
      - db-proxy

  db-master:
    image: avr21/tfg-db-master
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - master-pgdata:/var/lib/postgresql/data
    networks:
      - passive-bridge
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 400M

  db-replica:
    image: avr21/tfg-db-replica
    restart: always
    env_file: .env
    environment:
      PRIMARY_HOST: ${PRIMARY_HOST}
      PRIMARY_PORT: ${PRIMARY_PORT}
      REPLICATION_USER: ${REPLICATION_USER}
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
    depends_on:
      - db-master
    volumes:
      - replica-pgdata:/var/lib/postgresql/data
    networks:
      - passive-bridge
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 400M

  db-proxy:
    image: avr21/tfg-db-proxy
    container_name: passive-db-proxy
    ports:
      - "5432:5432"
    depends_on:
      - db-master
      - db-replica
    networks:
      - passive-bridge

volumes:
  master-pgdata:
    name: master_pgdata
  replica-pgdata:
    name: replica_pgdata

networks:
  passive-bridge:
    driver: bridge
    name: passive_bridge