name: monitor

services:
  postgres-exporter-base:
    container_name: postgres-exporter-base
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      - DATA_SOURCE_NAME=postgresql://$BASE_DB_USER:$BASE_DB_PASSWORD@$BASE_DB_HOST:$BASE_DB_PORT/$BASE_DB_NAME?sslmode=disable
    networks:
      - monitor-net
  
  postgres-exporter-ha:
    container_name: postgres-exporter-ha
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      - DATA_SOURCE_NAME=postgresql://$HA_DB_USER:$HA_DB_PASSWORD@$HA_DB_HOST:$HA_DB_PORT/$HA_DB_NAME?sslmode=disable
    networks:
      - monitor-net

  prometheus:
    container_name: prometheus
    image: avr21/tfg-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitor-net
  
  grafana:
    container_name: grafana
    image: avr21/tfg-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    networks:
      - monitor-net

volumes:
  prometheus_data:

networks:
  monitor-net:
    driver: bridge
    name: monitor-net