name: dev
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   networks:
  #     - app-bridge
  #   environment:
  #     - HOST=0.0.0.0
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dev-bridge
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    env_file: .env #TODO - Set up github secret token
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-bridge

volumes:
  pgdata:
    name: pgdata

networks:
  dev-bridge:
    driver: bridge
    name: dev_bridge
