#syntax=docker/dockerfile:1
FROM node:slim

WORKDIR /usr/src/app

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends\
  build-essential \
  python3 \
  pkg-config \
  libpng-dev \
  libvips-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 1337

CMD ["npm", "run", "develop"]

