#syntax=docker/dockerfile:1
FROM node:lts-alpine

WORKDIR /usr/src/app

ENV DEBIAN_FRONTEND=noninteractive

RUN apk add --no-cache \
  build-base \
  python3 \
  pkgconf \
  libpng-dev \
  vips-dev


COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 1337

CMD ["npm", "run", "develop"]