global:
  scrape_interval: "5s"
  evaluation_interval: "5s"

scrape_configs:
  - job_name: 'base-db'
    static_configs:
      - targets: ['postgres-exporter-base:9187']
  - job_name: 'ha-db'
    static_configs:
      - targets: ['postgres-exporter-ha:9187']