name: Build and Push Backend Image

on:
  push:
    branches: [ "dev-back" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build tfg-backend image
        run: docker build ./backend --tag ${{ secrets.DOCKER_BACK_REPO }}
      
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Image push
        run: docker push ${{ secrets.DOCKER_BACK_REPO }}