name: Build and Push Base database image

on:
  push:
    branches: [ "dev-monitor" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Build tfg-prometheus image
        run: docker build ./stacks/monitor/prometheus --tag avr21/tfg-prometheus

      - name: Build tfg-grafana image
        run: docker build ./stacks/monitor/grafana --tag avr21/tfg-grafana

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push prometheus image
        run: docker push avr21/tfg-prometheus

      - name: Push grafana image
        run: docker push avr21/tfg-grafana